#!/usr/bin/env bash
# ─── scripts/lint-todo-markers.sh ────────────────────────────────────────────
# PD-21: Track TODO/FIXME/HACK markers in the backend codebase.
#
# These are pre-existing technical debt items. This script:
#   1. Lists all TODO/FIXME/HACK/PLACEHOLDER markers
#   2. Exits 0 (informational only — not a hard fail)
#   3. Output is appended to docs/todo-markers.md for tracking
#
#   bash scripts/lint-todo-markers.sh

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BACKEND_SRC="$ROOT/backend/src"
OUTPUT="$ROOT/backend/docs/todo-markers.md"

mkdir -p "$(dirname "$OUTPUT")"

echo "[lint-todo-markers] Scanning for TODO/FIXME/HACK markers..."

MARKERS=$(grep -rnE '(TODO|FIXME|HACK|PLACEHOLDER)' "$BACKEND_SRC" --include='*.ts' 2>/dev/null | grep -v '__tests__' | grep -v '.spec.ts' | grep -v '.test.ts' | grep -vE 'status.*=.*"TODO"|enum.*TODO' || true)

COUNT=$(echo "$MARKERS" | grep -c . || echo "0")

cat > "$OUTPUT" << 'EOF'
# TODO/FIXME/HACK Markers — Backend

Auto-generated by `scripts/lint-todo-markers.sh`. Tracks pre-existing technical debt.

| File | Line | Marker | Description |
|------|------|--------|-------------|
EOF

if [ -n "$MARKERS" ]; then
  while IFS= read -r match; do
    if [ -z "$match" ]; then continue; fi
    FILE=$(echo "$match" | cut -d: -f1 | sed "s|$ROOT/||")
    LINE=$(echo "$match" | cut -d: -f2)
    CONTENT=$(echo "$match" | cut -d: -f3- | sed 's/^ *//' | head -c 120)
    echo "| $FILE | $LINE | $CONTENT |" >> "$OUTPUT"
  done <<< "$MARKERS"
fi

echo "" >> "$OUTPUT"
echo "Total: **$COUNT** markers" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Last scan: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTPUT"

echo "  Found $COUNT markers → $OUTPUT"
echo "[lint-todo-markers] OK"
exit 0
