import { Module, OnModuleInit, forwardRef, Logger } from '@nestjs/common';
import { ToolsController } from './tools.controller';
import { ToolsService } from './tools.service';
import { StructuredToolRegistry } from './structured-tool.registry';
import { HttpRequestTool } from './built-in/http-request.tool';
import { CalculatorTool } from './built-in/calculator.tool';
import { CalculatorEnhancedTool } from './built-in/calculator-enhanced.tool';
import { HttpRequestEnhancedTool } from './built-in/http-request-enhanced.tool';
import { EmailTool } from './built-in/email.tool';
import { DocumentsTool } from './built-in/documents.tool';
import { ReportsTool } from './built-in/reports.tool';
import { QueryTool } from './built-in/query.tool';
import { ExplainTool } from './built-in/explain.tool';
import { ContextTool } from './built-in/context.tool';
import { ChatTool } from './built-in/chat.tool';
import { CalendarTool } from './built-in/calendar.tool';
import { SheetsTool } from './built-in/sheets.tool';
import { IntegrationsModule } from '../integrations/integrations.module';
import { ModelsModule } from '../models/models.module';
import { MemoryModule } from '../memory/memory.module';
import {
  CreateTaskTool,
  CreateProjectTool,
  ListDepartmentsTool,
  ListAgentsTool,
  PauseAgentTool,
  ResumeAgentTool,
  ListTasksTool,
  GetTenantSnapshotTool,
  UpdateDepartmentTool,
  ArchiveDepartmentTool,
  DeleteDepartmentTool,
  AssignManagerTool,
  UnassignManagerTool,
  GetAgentTool,
  UpdateAgentTool,
  ArchiveAgentTool,
  AssignAgentToDepartmentTool,
  RemoveAgentFromProjectTool,
  BulkCreateAgentsTool,
  BulkAssignToDepartmentTool,
  GetAgentWorkloadTool,
  GetProjectTool,
  UpdateProjectTool,
  ArchiveProjectTool,
  DeleteProjectTool,
  CloneProjectTool,
  GetTaskTool,
  UpdateTaskTool,
  DeleteTaskTool,
  AssignTaskTool,
  UnassignTaskTool,
  MarkTaskCompleteTool,
  MarkTaskInProgressTool,
  ReopenTaskTool,
  ChangeTaskPriorityTool,
  AddSubtaskTool,
  ListSubtasksTool,
  GetMyTasksTool,
  GetOverdueTasksTool,
  BulkAssignTasksTool,
  BulkChangeStatusTool,
  CloneTaskTool,
  ListPendingApprovalsTool,
  GetApprovalTool,
  ApproveRequestTool,
  RejectRequestTool,
  BulkApproveTool,
  BulkRejectTool,
  CreateApprovalRequestTool,
  GetMyPendingApprovalsTool,
  ResubmitApprovalTool,
  CancelApprovalRequestTool,
  GetCostReportTool,
  GetCostByDepartmentTool,
  GetCostByAgentTool,
  GetCostByProjectTool,
  SetBudgetAlertTool,
  GetTodayCostTool,
  GetCompanyProfileTool,
  UpdateCompanyProfileTool,
  GetTenantSettingsTool,
  GetMyNotificationsTool,
  MarkNotificationReadTool,
  MarkAllNotificationsReadTool,
  GetDashboardSummaryTool,
  GetOverdueTaskReportTool,
  GetInboxSummaryTool,
  ListInboxItemsTool,
  GetInboxItemTool,
  RespondToInboxItemTool,
} from './built-in/neurecore-tools';
import type { IStructuredTool } from './interfaces/structured-tool.interface';

@Module({
  imports: [forwardRef(() => IntegrationsModule), ModelsModule, MemoryModule],
  controllers: [ToolsController],
  providers: [
    HttpRequestTool,
    CalculatorTool,
    CalculatorEnhancedTool,
    HttpRequestEnhancedTool,
    EmailTool,
    DocumentsTool,
    ReportsTool,
    QueryTool,
    ExplainTool,
    ContextTool,
    ChatTool,
    CalendarTool,
    SheetsTool,
    CreateTaskTool,
    CreateProjectTool,
    ListDepartmentsTool,
    ListAgentsTool,
    PauseAgentTool,
    ResumeAgentTool,
    ListTasksTool,
    GetTenantSnapshotTool,
    UpdateDepartmentTool,
    ArchiveDepartmentTool,
    DeleteDepartmentTool,
    AssignManagerTool,
    UnassignManagerTool,
    GetAgentTool,
    UpdateAgentTool,
    ArchiveAgentTool,
    AssignAgentToDepartmentTool,
    RemoveAgentFromProjectTool,
    BulkCreateAgentsTool,
    BulkAssignToDepartmentTool,
    GetAgentWorkloadTool,
    GetProjectTool,
    UpdateProjectTool,
    ArchiveProjectTool,
    DeleteProjectTool,
    CloneProjectTool,
    GetTaskTool,
    UpdateTaskTool,
    DeleteTaskTool,
    AssignTaskTool,
    UnassignTaskTool,
    MarkTaskCompleteTool,
    MarkTaskInProgressTool,
    ReopenTaskTool,
    ChangeTaskPriorityTool,
    AddSubtaskTool,
    ListSubtasksTool,
    GetMyTasksTool,
    GetOverdueTasksTool,
    BulkAssignTasksTool,
    BulkChangeStatusTool,
    CloneTaskTool,
    ListPendingApprovalsTool,
    GetApprovalTool,
    ApproveRequestTool,
    RejectRequestTool,
    BulkApproveTool,
    BulkRejectTool,
    CreateApprovalRequestTool,
    GetMyPendingApprovalsTool,
    ResubmitApprovalTool,
    CancelApprovalRequestTool,
    GetCostReportTool,
    GetCostByDepartmentTool,
    GetCostByAgentTool,
    GetCostByProjectTool,
    SetBudgetAlertTool,
    GetTodayCostTool,
    GetCompanyProfileTool,
    UpdateCompanyProfileTool,
    GetTenantSettingsTool,
    GetMyNotificationsTool,
    MarkNotificationReadTool,
    MarkAllNotificationsReadTool,
    GetDashboardSummaryTool,
    GetOverdueTaskReportTool,
    GetInboxSummaryTool,
    ListInboxItemsTool,
    GetInboxItemTool,
    RespondToInboxItemTool,
    ToolsService,
    StructuredToolRegistry,
  ],
  exports: [ToolsService, StructuredToolRegistry],
})
export class ToolsModule implements OnModuleInit {
  constructor(
    private readonly registry: StructuredToolRegistry,
    private readonly httpTool: HttpRequestTool,
    private readonly calcTool: CalculatorTool,
    private readonly calcEnhanced: CalculatorEnhancedTool,
    private readonly httpEnhanced: HttpRequestEnhancedTool,
    private readonly emailTool: EmailTool,
    private readonly documentsTool: DocumentsTool,
    private readonly reportsTool: ReportsTool,
    private readonly queryTool: QueryTool,
    private readonly explainTool: ExplainTool,
    private readonly contextTool: ContextTool,
    private readonly chatTool: ChatTool,
    private readonly calendarTool: CalendarTool,
    private readonly sheetsTool: SheetsTool,
    private readonly createTask: CreateTaskTool,
    private readonly createProject: CreateProjectTool,
    private readonly listDepts: ListDepartmentsTool,
    private readonly listAgents: ListAgentsTool,
    private readonly pauseAgent: PauseAgentTool,
    private readonly resumeAgent: ResumeAgentTool,
    private readonly listTasks: ListTasksTool,
    private readonly getSnapshot: GetTenantSnapshotTool,
    private readonly updateDept: UpdateDepartmentTool,
    private readonly archiveDept: ArchiveDepartmentTool,
    private readonly deleteDept: DeleteDepartmentTool,
    private readonly assignMgr: AssignManagerTool,
    private readonly unassignMgr: UnassignManagerTool,
    private readonly getAgent: GetAgentTool,
    private readonly updateAgent: UpdateAgentTool,
    private readonly archiveAgent: ArchiveAgentTool,
    private readonly assignAgentToDept: AssignAgentToDepartmentTool,
    private readonly removeAgentFromProject: RemoveAgentFromProjectTool,
    private readonly bulkCreateAgents: BulkCreateAgentsTool,
    private readonly bulkAssignToDept: BulkAssignToDepartmentTool,
    private readonly getAgentWorkload: GetAgentWorkloadTool,
    private readonly getProject: GetProjectTool,
    private readonly updateProject: UpdateProjectTool,
    private readonly archiveProject: ArchiveProjectTool,
    private readonly deleteProject: DeleteProjectTool,
    private readonly cloneProject: CloneProjectTool,
    private readonly getTask: GetTaskTool,
    private readonly updateTask: UpdateTaskTool,
    private readonly deleteTask: DeleteTaskTool,
    private readonly assignTask: AssignTaskTool,
    private readonly unassignTask: UnassignTaskTool,
    private readonly markTaskComplete: MarkTaskCompleteTool,
    private readonly markTaskInProgress: MarkTaskInProgressTool,
    private readonly reopenTask: ReopenTaskTool,
    private readonly changeTaskPriority: ChangeTaskPriorityTool,
    private readonly addSubtask: AddSubtaskTool,
    private readonly listSubtasks: ListSubtasksTool,
    private readonly getMyTasks: GetMyTasksTool,
    private readonly getOverdueTasks: GetOverdueTasksTool,
    private readonly bulkAssignTasks: BulkAssignTasksTool,
    private readonly bulkChangeStatus: BulkChangeStatusTool,
    private readonly cloneTask: CloneTaskTool,
    private readonly listPendingApprovals: ListPendingApprovalsTool,
    private readonly getApproval: GetApprovalTool,
    private readonly approveRequest: ApproveRequestTool,
    private readonly rejectRequest: RejectRequestTool,
    private readonly bulkApprove: BulkApproveTool,
    private readonly bulkReject: BulkRejectTool,
    private readonly createApprovalRequest: CreateApprovalRequestTool,
    private readonly getMyPendingApprovals: GetMyPendingApprovalsTool,
    private readonly resubmitApproval: ResubmitApprovalTool,
    private readonly cancelApprovalRequest: CancelApprovalRequestTool,
    private readonly getCostReport: GetCostReportTool,
    private readonly getCostByDept: GetCostByDepartmentTool,
    private readonly getCostByAgent: GetCostByAgentTool,
    private readonly getCostByProject: GetCostByProjectTool,
    private readonly setBudgetAlert: SetBudgetAlertTool,
    private readonly getTodayCost: GetTodayCostTool,
    private readonly getCompanyProfile: GetCompanyProfileTool,
    private readonly updateCompanyProfile: UpdateCompanyProfileTool,
    private readonly getTenantSettings: GetTenantSettingsTool,
    private readonly getMyNotifications: GetMyNotificationsTool,
    private readonly markNotificationRead: MarkNotificationReadTool,
    private readonly markAllNotificationsRead: MarkAllNotificationsReadTool,
    private readonly getDashboardSummary: GetDashboardSummaryTool,
    private readonly getOverdueTaskReport: GetOverdueTaskReportTool,
    private readonly getInboxSummary: GetInboxSummaryTool,
    private readonly listInboxItems: ListInboxItemsTool,
    private readonly getInboxItem: GetInboxItemTool,
    private readonly respondToInboxItem: RespondToInboxItemTool,
  ) {
    this.logger = new Logger(ToolsModule.name);
  }

  private readonly logger = new Logger(ToolsModule.name);

  onModuleInit(): void {
    const tools: IStructuredTool[] = [
      this.httpTool,
      this.calcTool,
      this.calcEnhanced,
      this.httpEnhanced,
      this.emailTool,
      this.documentsTool,
      this.reportsTool,
      this.queryTool,
      this.explainTool,
      this.contextTool,
      this.chatTool,
      this.calendarTool,
      this.sheetsTool,
      this.createTask,
      this.createProject,
      this.listDepts,
      this.listAgents,
      this.pauseAgent,
      this.resumeAgent,
      this.listTasks,
      this.getSnapshot,
      this.updateDept,
      this.archiveDept,
      this.deleteDept,
      this.assignMgr,
      this.unassignMgr,
      this.getAgent,
      this.updateAgent,
      this.archiveAgent,
      this.assignAgentToDept,
      this.removeAgentFromProject,
      this.bulkCreateAgents,
      this.bulkAssignToDept,
      this.getAgentWorkload,
      this.getProject,
      this.updateProject,
      this.archiveProject,
      this.deleteProject,
      this.cloneProject,
      this.getTask,
      this.updateTask,
      this.deleteTask,
      this.assignTask,
      this.unassignTask,
      this.markTaskComplete,
      this.markTaskInProgress,
      this.reopenTask,
      this.changeTaskPriority,
      this.addSubtask,
      this.listSubtasks,
      this.getMyTasks,
      this.getOverdueTasks,
      this.bulkAssignTasks,
      this.bulkChangeStatus,
      this.cloneTask,
      this.listPendingApprovals,
      this.getApproval,
      this.approveRequest,
      this.rejectRequest,
      this.bulkApprove,
      this.bulkReject,
      this.createApprovalRequest,
      this.getMyPendingApprovals,
      this.resubmitApproval,
      this.cancelApprovalRequest,
      this.getCostReport,
      this.getCostByDept,
      this.getCostByAgent,
      this.getCostByProject,
      this.setBudgetAlert,
      this.getTodayCost,
      this.getCompanyProfile,
      this.updateCompanyProfile,
      this.getTenantSettings,
      this.getMyNotifications,
      this.markNotificationRead,
      this.markAllNotificationsRead,
      this.getDashboardSummary,
      this.getOverdueTaskReport,
      this.getInboxSummary,
      this.listInboxItems,
      this.getInboxItem,
      this.respondToInboxItem,
    ].filter((t) => t !== null && t !== undefined) as IStructuredTool[];

    this.logger.log(`[ToolsModule] filtered tools count: ${tools.length}`);
    this.registry.setTools(tools);
    this.logger.log(`[ToolsModule] setTools called with ${tools.length} tools`);
  }
}
