/**
 * Built-in widget definitions — the canonical Widget library.
 *
 * Phase 4 / EAOS-2 ships these 12 widget definitions out of the box.
 * Additional widgets can be added by Solution Packs (Phase 7) via
 * `WidgetRegistry.register()`.
 *
 * Each definition is the 4-layer contract (Capability → Data Source →
 * Aggregation → Visualization) per `EAOS-implementation-plan.md` §3.3.
 */

import type { WidgetDefinition } from './widget-definition';

export const BUILT_IN_WIDGETS: ReadonlyArray<WidgetDefinition> = [
  // 1 — Revenue CARD
  {
    id: 'financial-revenue-card',
    capability: 'FINANCIAL_PERFORMANCE',
    capabilityDomain: 'financial',
    dataSources: [{ entity: 'PROJECT', field: 'completedValue' }],
    aggregationType: 'SUM',
    computation: 'revenueSum',
    visualizations: ['CARD', 'SPARKLINE'],
    defaultVisualization: 'CARD',
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    defaultSize: { w: 3, h: 2 },
    configurableFields: [
      {
        key: 'timeRange',
        label: 'Time range',
        type: 'select',
        defaultValue: '30d',
        options: [
          { value: '7d', label: 'Last 7 days' },
          { value: '30d', label: 'Last 30 days' },
          { value: '90d', label: 'Last 90 days' },
          { value: 'ytd', label: 'Year to date' },
        ],
      },
    ],
    refreshInterval: 60_000,
    title: 'Revenue',
    subtitle: 'Sum of completed task values',
    icon: 'dollar-sign',
    entityTypes: ['PROJECT', 'DEPARTMENT', 'AGENT'],
    category: 'CORE',
  },

  // 2 — Revenue LINE CHART
  {
    id: 'financial-revenue-trend',
    capability: 'FINANCIAL_PERFORMANCE',
    capabilityDomain: 'financial',
    dataSources: [{ entity: 'PROJECT', field: 'completedValue' }],
    aggregationType: 'SUM',
    computation: 'revenueByDay',
    visualizations: ['LINE_CHART', 'BAR_CHART'],
    defaultVisualization: 'LINE_CHART',
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 6 },
    defaultSize: { w: 6, h: 4 },
    configurableFields: [
      {
        key: 'days',
        label: 'Days',
        type: 'number',
        defaultValue: 30,
      },
    ],
    refreshInterval: 300_000,
    title: 'Revenue trend',
    icon: 'trending-up',
    entityTypes: ['PROJECT', 'DEPARTMENT', 'AGENT'],
    category: 'CORE',
  },

  // 3 — Active Tasks CARD (operational)
  {
    id: 'operational-active-tasks-card',
    capability: 'OPERATIONAL_EFFICIENCY',
    capabilityDomain: 'operational',
    dataSources: [{ entity: 'TASK', field: 'status' }],
    aggregationType: 'COUNT',
    computation: 'taskCountByStatus:active',
    visualizations: ['CARD', 'SPARKLINE'],
    defaultVisualization: 'CARD',
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    defaultSize: { w: 3, h: 2 },
    configurableFields: [],
    refreshInterval: 30_000,
    title: 'Active tasks',
    icon: 'list-checks',
    entityTypes: [
      'AGENT',
      'DEPARTMENT',
      'PROJECT',
      'GOAL',
      'WORKFLOW',
      'ROUTINE',
    ],
    category: 'CORE',
  },

  // 4 — Task Completion Rate GAUGE
  {
    id: 'operational-completion-gauge',
    capability: 'OPERATIONAL_EFFICIENCY',
    capabilityDomain: 'operational',
    dataSources: [{ entity: 'TASK', field: 'status' }],
    aggregationType: 'PERCENTAGE',
    computation: 'taskCompletionRate',
    visualizations: ['GAUGE', 'CARD'],
    defaultVisualization: 'GAUGE',
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 5 },
    defaultSize: { w: 4, h: 4 },
    configurableFields: [
      {
        key: 'timeRange',
        label: 'Time range',
        type: 'select',
        defaultValue: '30d',
        options: [
          { value: '7d', label: 'Last 7 days' },
          { value: '30d', label: 'Last 30 days' },
          { value: '90d', label: 'Last 90 days' },
        ],
      },
    ],
    refreshInterval: 60_000,
    title: 'Completion rate',
    icon: 'gauge',
    entityTypes: ['AGENT', 'DEPARTMENT', 'PROJECT', 'GOAL'],
    category: 'CORE',
  },

  // 5 — AI Cost CARD
  {
    id: 'ai-cost-card',
    capability: 'AI_PERFORMANCE',
    capabilityDomain: 'ai',
    dataSources: [{ entity: 'AGENT', field: 'dailyCost' }],
    aggregationType: 'SUM',
    computation: 'aiDailyCost',
    visualizations: ['CARD', 'SPARKLINE'],
    defaultVisualization: 'CARD',
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    defaultSize: { w: 3, h: 2 },
    configurableFields: [],
    refreshInterval: 60_000,
    title: 'AI cost today',
    icon: 'cpu',
    entityTypes: ['AGENT', 'DEPARTMENT', 'PROJECT'],
    category: 'CORE',
  },

  // 6 — AI Tasks Completed TABLE
  {
    id: 'ai-tasks-table',
    capability: 'AI_PERFORMANCE',
    capabilityDomain: 'ai',
    dataSources: [{ entity: 'AGENT', field: 'tasksCompleted' }],
    aggregationType: 'COUNT',
    computation: 'aiTasksCompleted',
    visualizations: ['TABLE', 'BAR_CHART'],
    defaultVisualization: 'TABLE',
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 8 },
    defaultSize: { w: 6, h: 4 },
    configurableFields: [],
    refreshInterval: 120_000,
    title: 'AI performance',
    icon: 'bar-chart-3',
    entityTypes: ['DEPARTMENT', 'PROJECT'],
    category: 'CORE',
  },

  // 7 — Risk Heatmap (single widget, custom aggregation)
  {
    id: 'risk-posture-heatmap',
    capability: 'RISK_POSTURE',
    capabilityDomain: 'risk',
    dataSources: [{ entity: 'PROJECT', field: 'riskScore' }],
    aggregationType: 'CUSTOM',
    computation: 'riskBySeverity',
    visualizations: ['HEATMAP', 'TABLE'],
    defaultVisualization: 'HEATMAP',
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 6 },
    defaultSize: { w: 6, h: 4 },
    configurableFields: [],
    refreshInterval: 300_000,
    title: 'Risk posture',
    icon: 'shield-alert',
    entityTypes: ['DEPARTMENT', 'PROJECT', 'GOAL'],
    category: 'CORE',
  },

  // 8 — Customer Health GAUGE
  {
    id: 'customer-health-gauge',
    capability: 'CUSTOMER_HEALTH',
    capabilityDomain: 'customer',
    dataSources: [{ entity: 'PROJECT', field: 'npsScore' }],
    aggregationType: 'AVG',
    computation: 'npsAverage',
    visualizations: ['GAUGE', 'CARD'],
    defaultVisualization: 'GAUGE',
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 5 },
    defaultSize: { w: 4, h: 4 },
    configurableFields: [],
    refreshInterval: 300_000,
    title: 'Customer NPS',
    icon: 'heart',
    entityTypes: ['DEPARTMENT', 'PROJECT'],
    category: 'CORE',
  },

  // 9 — Workforce Status GRID (headcount)
  {
    id: 'workforce-headcount-grid',
    capability: 'WORKFORCE_STATUS',
    capabilityDomain: 'workforce',
    dataSources: [{ entity: 'AGENT', field: 'status' }],
    aggregationType: 'COUNT',
    computation: 'headcountByStatus',
    visualizations: ['GRID', 'TABLE', 'STATUS_BADGE'],
    defaultVisualization: 'GRID',
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 4 },
    defaultSize: { w: 4, h: 3 },
    configurableFields: [],
    refreshInterval: 60_000,
    title: 'Workforce',
    icon: 'users',
    entityTypes: ['DEPARTMENT', 'PROJECT'],
    category: 'CORE',
  },

  // 10 — Knowledge Entries COUNT CARD
  {
    id: 'knowledge-count-card',
    capability: 'KNOWLEDGE_ACCESS',
    capabilityDomain: 'knowledge',
    dataSources: [{ entity: 'KNOWLEDGE', field: 'id' }],
    aggregationType: 'COUNT',
    computation: 'knowledgeCount',
    visualizations: ['CARD'],
    defaultVisualization: 'CARD',
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    defaultSize: { w: 3, h: 2 },
    configurableFields: [],
    refreshInterval: 300_000,
    title: 'Knowledge entries',
    icon: 'book',
    entityTypes: ['DEPARTMENT', 'PROJECT', 'AGENT'],
    category: 'CORE',
  },

  // 11 — Automation Status COUNT
  {
    id: 'automation-count-card',
    capability: 'AUTOMATION_STATUS',
    capabilityDomain: 'automation',
    dataSources: [{ entity: 'WORKFLOW', field: 'id' }],
    aggregationType: 'COUNT',
    computation: 'workflowCount',
    visualizations: ['CARD', 'SPARKLINE'],
    defaultVisualization: 'CARD',
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    defaultSize: { w: 3, h: 2 },
    configurableFields: [],
    refreshInterval: 60_000,
    title: 'Active workflows',
    icon: 'workflow',
    entityTypes: ['DEPARTMENT', 'PROJECT', 'AGENT'],
    category: 'CORE',
  },

  // 12 — Compliance STATUS_BADGE
  {
    id: 'compliance-status-badge',
    capability: 'COMPLIANCE_STATUS',
    capabilityDomain: 'compliance',
    dataSources: [{ entity: 'DEPARTMENT', field: 'complianceStatus' }],
    aggregationType: 'CUSTOM',
    computation: 'complianceStatus',
    visualizations: ['STATUS_BADGE', 'CARD'],
    defaultVisualization: 'STATUS_BADGE',
    minSize: { w: 2, h: 1 },
    maxSize: { w: 4, h: 2 },
    defaultSize: { w: 2, h: 1 },
    configurableFields: [],
    refreshInterval: 600_000,
    title: 'Compliance',
    icon: 'shield-check',
    entityTypes: ['DEPARTMENT', 'PROJECT'],
    category: 'CORE',
  },
];