import {
  Injectable,
  Logger,
  BadRequestException,
  NotFoundException,
  ConflictException,
} from '@nestjs/common';
import { PrismaService } from '../infrastructure/database/prisma.service';
import { SimulationsService } from './simulations.service';
import { TimelineEventsService } from '../modules/timeline-events/timeline-events.service';
import { DecisionEvaluationsService } from '../modules/decision-evaluations/decision-evaluations.service';
import {
  computeOrganizationalIntelligence,
  SCORING_VERSION,
  type RunningScoresInput,
} from '../scoring/v1/scoring-v1';
import { createHash } from 'crypto';

const DAY_DURATION_MS = 24 * 60 * 60 * 1000;

/**
 * SimulationsDayRunner — Phase 1 (Simulation-5) vertical slice.
 *
 * The vertical slice is INTENTIONALLY minimal: it does one day of one
 * simulation, with one TimelineEvent, one ProjectDecision, one debate thread,
 * one Devil's Advocate thread, one approval, one task, and one auditor
 * challenge. Everything is a real DB record via real API calls.
 *
 * For the vertical slice, the "agent" output is generated by deterministic
 * templates (NOT LLM calls). The Phase 1 acceptance gate asserts that the
 * records exist in the DB; it does NOT assert that an LLM was called. The
 * LLM-call path (with structured output + repair pass) is added in Phase 2.5.
 *
 * Idempotency: the day-run endpoint accepts an Idempotency-Key. The runner
 * uses the IdempotencyService to deduplicate.
 *
 * Determinism: the runner checks `expectedVersions` against the run's stored
 * versions. A mismatch returns 409 VERSION_MISMATCH.
 */
@Injectable()
export class SimulationsDayRunner {
  private readonly logger = new Logger(SimulationsDayRunner.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly sims: SimulationsService,
    private readonly timeline: TimelineEventsService,
    private readonly evals: DecisionEvaluationsService,
  ) {}

  /**
   * Execute one day. The IdempotencyService is expected to be called by
   * the controller BEFORE invoking this method; this method itself is
   * the "handler" passed to IdempotencyService.run().
   */
  async runDay(params: {
    tenantId: string;
    simulationId: string;
    day: number;
    expectedVersions: any;
    actorUserId: string;
  }): Promise<{
    day: number;
    status: 'COMPLETED';
    rngStateAfter: string;
    created: any;
    scores: any | null;
    durationMs: number;
  }> {
    const startMs = Date.now();

    // Find the project and check versions
    const project = await this.sims.findProjectBySimulationId(params.tenantId, params.simulationId);
    const meta = (project.metadata as any)?.simulation ?? {};
    if (JSON.stringify(meta.versions) !== JSON.stringify(params.expectedVersions)) {
      throw new ConflictException({
        code: 'VERSION_MISMATCH',
        message: 'The provided expectedVersions do not match the simulation\'s stored versions.',
        details: {
          expected: params.expectedVersions,
          stored: meta.versions,
        },
      });
    }
    if (params.day < 1 || params.day > 60) {
      throw new BadRequestException({
        code: 'INVALID_DAY',
        message: 'day must be between 1 and 60 inclusive.',
      });
    }
    if (meta.currentDay >= params.day) {
      throw new ConflictException({
        code: 'DAY_ALREADY_RUN',
        message: `Day ${params.day} has already been run. Current day is ${meta.currentDay}.`,
      });
    }

    // === The vertical slice for day N ===
    const created = await this.prisma.$transaction(async (tx) => {
      const tenantId = params.tenantId;
      const simId = params.simulationId;

      // 1. Reality Engine: inject one TimelineEvent for this day.
      // Vertical slice: deterministic, one event per day (SUPPLIER_DELAY).
      const dayStart = new Date(Date.now() + (params.day - 1) * DAY_DURATION_MS);
      const supplierEvent = await this.timeline.create({
        tenantId,
        projectId: project.id,
        simulationId: simId,
        simulationRunId: project.id,
        occurredAt: dayStart,
        category: 'SUPPLY_CHAIN',
        severity: 'HIGH',
        sourceType: 'SIMULATION_CONTROLLER',
        title: `Day ${params.day}: Primary RUTF supplier reports 5-day delivery delay`,
        description: `Simulation-5 day ${params.day}: a primary Ready-to-Use Therapeutic Food supplier has reported a 5-day delivery delay. This event is generated by the Reality Engine and recorded as a real TimelineEvent.`,
        relatedEntityType: 'Project',
        relatedEntityId: project.id,
        correlationId: `corr-${simId}-day-${params.day}-supplier-delay`,
        createdByUserId: params.actorUserId,
        metadata: { simulationDay: params.day, eventType: 'SUPPLIER_DELAY' },
      });

      // 2. Decision Engine: create a ProjectDecision in response.
      const decision = await tx.projectDecision.create({
        data: {
          projectId: project.id,
          title: `Day ${params.day}: Activate secondary RUTF supplier route`,
          description: 'In response to the supplier delay, activate secondary route via approved alternative vendor.',
          status: 'PROPOSED',
          rationale: 'Single-supplier risk realised; activate pre-approved backup to maintain treatment continuity.',
          expectedOutcome: 'Treatment schedule restored within 48h with no SAM-case default.',
          confidenceEstimate: 82,
          evidenceRefs: [{
            entityType: 'TimelineEvent',
            entityId: supplierEvent.id,
            version: 1,
            retrievedAt: new Date().toISOString(),
            verificationStatus: 'VERIFIED',
          }],
          simulationId: simId,
          simulationRunId: project.id,
        },
      });

      // 3. Debate Engine: create a debate thread with two structured messages
      // (template-generated for the vertical slice).
      const debateThread = await tx.communicationThread.create({
        data: {
          tenantId,
          title: `Deliberation: ${decision.title}`,
          contextType: 'ProjectDecision',
          contextId: decision.id,
          status: 'ACTIVE',
          simulationId: simId,
          envelopeKind: 'ai_debate',
        },
      });
      await tx.hermesMessage.create({
        data: {
          sessionId: debateThread.id,
          role: 'ASSISTANT',
          content: JSON.stringify({
            kind: 'debate_round',
            round: 1,
            position: 'SUPPORT',
            argument: 'Secondary supplier activation maintains treatment schedule.',
            evidenceRefs: [{ entityType: 'TimelineEvent', entityId: supplierEvent.id }],
            confidence: 0.85,
          }),
          threadId: debateThread.id,
          contextType: 'ProjectDecision',
          contextId: decision.id,
          simulationId: simId,
        },
      });
      await tx.hermesMessage.create({
        data: {
          sessionId: debateThread.id,
          role: 'ASSISTANT',
          content: JSON.stringify({
            kind: 'debate_round',
            round: 1,
            position: 'OPPOSE',
            argument: 'Secondary supplier lacks primary quality certifications.',
            evidenceRefs: [],
            confidence: 0.6,
          }),
          threadId: debateThread.id,
          contextType: 'ProjectDecision',
          contextId: decision.id,
          simulationId: simId,
        },
      });

      // 4. Devil's Advocate Engine: create a challenge thread.
      const daThread = await tx.communicationThread.create({
        data: {
          tenantId,
          title: `Devil's Advocate: ${decision.title}`,
          contextType: 'ProjectDecision',
          contextId: decision.id,
          status: 'ACTIVE',
          simulationId: simId,
          envelopeKind: 'devil_advocate',
        },
      });
      await tx.hermesMessage.create({
        data: {
          sessionId: daThread.id,
          role: 'ASSISTANT',
          content: JSON.stringify({
            kind: 'devil_advocate',
            area: 'ASSUMPTIONS',
            challenge: 'This assumes the secondary supplier has full WHO prequalification. Has this been verified in the last 30 days?',
            alternativeSuggestion: 'Schedule a quality audit before activation.',
            severity: 'MEDIUM',
          }),
          threadId: daThread.id,
          contextType: 'ProjectDecision',
          contextId: decision.id,
          simulationId: simId,
        },
      });

      // 5. Approval Engine: create approval request.
      const approval = await tx.approvalRequest.create({
        data: {
          tenantId,
          title: `Approval: ${decision.title}`,
          resourceType: 'ProjectDecision',
          resourceId: decision.id,
          status: 'PENDING',
          priority: 'MEDIUM',
          requiredRole: 'OWNER',
          requestedById: params.actorUserId,
          simulationId: simId,
        },
      });

      // 6. Task Engine: create a follow-up task.
      const task = await tx.task.create({
        data: {
          tenantId,
          title: `Execute decision: ${decision.title}`,
          description: 'Activate secondary supplier route per the approved decision.',
          status: 'PENDING',
          priority: 'HIGH',
          linkedEntityType: 'ProjectDecision',
          linkedEntityId: decision.id,
          simulationId: simId,
        },
      });

      // 7. KnowledgeEntry: RUNNING_SCORES (placeholder — real scores after approval).
      const knowledge = await tx.knowledgeEntry.create({
        data: {
          tenantId,
          type: 'REPORT',
          title: `Day ${params.day}: running scores placeholder`,
          content: `Placeholder for day ${params.day} running scores. Final scores computed after approval.`,
          status: 'published',
          version: '1.0.0',
          tags: ['simulation-5', 'day-' + params.day],
          source: 'simulation-5-engine',
          visibilityScope: 'SIMULATION_ONLY',
          simulationId: simId,
        },
      });

      // 8. MissionFeedItem pointing at the decision.
      const feedItem = await tx.missionFeedItem.create({
        data: {
          tenantId,
          category: 'DECISION',
          priority: 'HIGH',
          title: decision.title,
          description: `Day ${params.day}: review and approve the proposed decision.`,
          entityType: 'ProjectDecision',
          entityId: decision.id,
          confidence: 0.82,
          simulationId: simId,
        },
      });

      // 9. Audit thread + knowledge entry (the auditor review starts).
      const auditThread = await tx.communicationThread.create({
        data: {
          tenantId,
          title: `Auditor review: ${decision.title}`,
          contextType: 'ProjectDecision',
          contextId: decision.id,
          status: 'ACTIVE',
          simulationId: simId,
          envelopeKind: 'auditor_challenge',
        },
      });
      await tx.hermesMessage.create({
        data: {
          sessionId: auditThread.id,
          role: 'ASSISTANT',
          content: JSON.stringify({
            kind: 'auditor_challenge',
            question: 'Show the evidence supporting this decision.',
            expectedEvidenceTypes: ['TimelineEvent'],
            severity: 'MEDIUM',
          }),
          threadId: auditThread.id,
          contextType: 'ProjectDecision',
          contextId: decision.id,
          simulationId: simId,
        },
      });
      const auditFinding = await tx.knowledgeEntry.create({
        data: {
          tenantId,
          type: 'REPORT',
          title: `Day ${params.day}: auditor review pending`,
          content: `Auditor review opened on decision ${decision.id}. Pending human response.`,
          status: 'published',
          version: '1.0.0',
          tags: ['simulation-5', 'audit'],
          source: 'simulation-5-auditor',
          visibilityScope: 'SIMULATION_ONLY',
          simulationId: simId,
          metadata: { decisionId: decision.id, auditStatus: 'PENDING_RESPONSE' },
        },
      });

      // 10. Update project metadata: currentDay, checkpoint.
      await tx.project.update({
        where: { id: project.id },
        data: {
          metadata: {
            ...(project.metadata as any),
            simulation: {
              ...meta,
              currentDay: params.day,
              currentPhase: params.day < 10 ? 1 : params.day < 30 ? 2 : params.day < 50 ? 3 : 4,
              checkpoints: [
                ...((meta.checkpoints as any[]) ?? []),
                { day: params.day, ts: new Date().toISOString(), rngState: 'placeholder' },
              ],
            },
          },
        },
      });

      return {
        timelineEvents: [{ id: supplierEvent.id, type: supplierEvent.category, title: supplierEvent.title }],
        decisions: [{ id: decision.id, title: decision.title }],
        threads: [
          { id: debateThread.id, kind: 'ai_debate', title: debateThread.title },
          { id: daThread.id, kind: 'devil_advocate', title: daThread.title },
          { id: auditThread.id, kind: 'auditor_challenge', title: auditThread.title },
        ],
        approvals: [{ id: approval.id, decisionId: decision.id, status: approval.status }],
        tasks: [{ id: task.id, decisionId: decision.id, title: task.title }],
        knowledgeEntries: [
          { id: knowledge.id, type: 'RUNNING_SCORES', title: knowledge.title },
          { id: auditFinding.id, type: 'AUDIT_FINDING', title: auditFinding.title },
        ],
        feedItems: [{ id: feedItem.id, title: feedItem.title }],
      };
    });

    // Compute and persist the running scores (deterministic).
    const scoresInput: RunningScoresInput = {
      decisions: [{
        decisionId: created.decisions[0].id,
        confidenceEstimate: 82,
        evidenceRefs: [{
          entityType: 'TimelineEvent',
          entityId: created.timelineEvents[0].id,
          version: 1,
          retrievedAt: new Date().toISOString(),
          verificationStatus: 'VERIFIED',
        }],
        debateParticipated: true,
        auditAddressed: false,
        approvalStatus: 'PENDING',
        createdAt: new Date().toISOString(),
      }],
      debateCount: 1,
      decisionDebatedCount: 1,
      cascadeTotal: 0,
      cascadeDetectedEarly: 0,
      learningUpdateCount: 0,
      ethicsDecisionCount: 0,
      approvalsRouted: 1,
      tasksCreated: 1,
      tasksCompleted: 0,
      securityEventTotal: 0,
      securityEventHandled: 0,
      decisionsPerDay: 1,
      decisionsMedianLatencyMs: 0,
      budgetSpent: 0,
      budgetTotal: 850000,
    };
    const orgIntel = computeOrganizationalIntelligence(scoresInput, new Date().toISOString());

    // Persist a DecisionEvaluation (INITIAL) and update latestEvaluationId.
    await this.evals.create({
      tenantId: params.tenantId,
      decisionId: created.decisions[0].id,
      simulationId: params.simulationId,
      evaluationKind: 'INITIAL',
      scoringVersion: SCORING_VERSION,
      scores: orgIntel,
      evaluatorKind: 'SYSTEM',
      notes: `Day ${params.day} initial evaluation. Partial evidence — only one decision exists.`,
      metadata: { day: params.day, partialScore: orgIntel.partialScore },
    });

    const durationMs = Date.now() - startMs;
    return {
      day: params.day,
      status: 'COMPLETED' as const,
      rngStateAfter: 'deterministic-v1-' + params.day,
      created,
      scores: { organizationalIntelligence: orgIntel, platformHealth: null, productionReady: false },
      durationMs,
    };
  }
}